spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/db-linkup
    username: sa
    password:
  sql.init.mode: always